### ISSUE TITLE
Storage Location For Bookmarks

### ISSUE THREAD

**Issue by ghost** [lubosz/radiotray#5]
Where is the customized bookmarks.xml file stored?  The /usr/share/radiotray/bookmarks.xml doesn't get updated, and I can't find a local copy in ~/home/user/.config.

**Comment by ottlinger** [comment]
Maybe you are checking the wrong location, my bookmarks and settings reside in:

```
~/.local/share/radiotray
```

**Comment by ghost** [comment]
That's it.  I should have searched for "radiotray" from ~/home/user.  Thanks!
